version: "5.0"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ifp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  scrapers:
    build:
      context: .
      dockerfile: docker/scrapers/Dockerfile
    container_name: scrapers
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./scrapers:/app
    command: python main.py

  dbt:
    build:
      context: .
      dockerfile: docker/dbt/Dockerfile
    container_name: dbt
    depends_on:
      - postgres
    volumes:
      - ./dbt:/dbt
    env_file:
      - .env
    command: dbt run

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    ports:
      - "8080:8080"
    environment:
      NC_DB: "pg://postgres:5432?u=app_user&p=app_password&d=app_db"  # todo : user & passwd
    depends_on:
      - postgres
    volumes:
      - nocodb_data:/usr/app/data

  nextjs:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
    depends_on:
      - nocodb
    env_file:
      - .env
    command: npm run dev

volumes:
  postgres_data:
  nocodb_data:

